---
- name: Update timezone and handle daylight savings time change
  hosts: 
    cisco_ios_switches
    cisco_iosxe_switches
  gather_facts: false
  become: true 
  tasks: 
    - name: send the time-related commands
      cisco.ios.ios_config:
        lines:
          - clock summer-time MST recurring
        before:
          - clock timezone MST -7

- name: Set the clock
  hosts: 
    cisco_ios_switches
    cisco_iosxe_switches
  gather_facts: false
  become: true 
  tasks:
    - name: output the current time
      ansible.builtin.script:
        cmd: /etc/ansible/playbooks/python_scripts
        executable: /usr/bin/python3
    - name: use this output to set time on cisco host
      cisco.ios.ios_command:
        commands:
          - clock set {{ lookup('ansible.builtin.file', '/etc/ansible/playbooks/timestamp_file') }}



